import { test } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';
import { validateCollectionFromJson } from './helpers/featured-products-helper';

// Read the JSON file generated by the scraper
const dataPath = path.join(process.cwd(), 'collections-with-urls.json');
const rawData = fs.readFileSync(dataPath, 'utf-8');
const regionsData: Record<string, { name: string, url: string }[]> = JSON.parse(rawData);

// Configure Playwright to run regions in parallel
test.describe.configure({ mode: 'parallel' });

test.describe('Data-Driven Featured Products Validation', () => {

    // List of collection names to skip (all lowercase)
    const collectionsToSkip = ['wizflo', 'colors', 'acacia supasleek'];

    for (const [regionCode, collections] of Object.entries(regionsData)) {
        if (collections.length === 0) continue;

        test(`Validate ${regionCode} Collections`, async ({ page }) => {
            test.setTimeout(300000);

            console.log(`🚀 Starting JSON-driven validation for: ${regionCode}`);

            for (const collection of collections) {

                const expectedName = collection.name.toLowerCase();
                
                // Skip collections known to have no Featured Products
                if (collectionsToSkip.includes(expectedName)) {
                    console.log(`⏭️  Skipping '${collection.name}' in ${regionCode} (Known to have no Featured Products).`);
                    continue;
                }

                await test.step(`Checking: ${collection.name}`, async () => {
                    // Call the helper function to perform the actual navigation and validation
                    await validateCollectionFromJson(page, regionCode, collection);
                });
            }
        });
    }
});